# Generated by Django 5.0.4 on 2024-04-10 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Vilnius', 'Vilnius'), ('Kaunas', 'Kaunas'), ('Klaipėda', 'Klaipeda'), ('Šiauliai', 'Siauliai'), ('Panevėžys', 'Panevezys'), ('Akmenė', 'Akmene'), ('Alytus', 'Alytus'), ('Anykščiai', 'Anyksciai'), ('Birštonas', 'Birstonas'), ('Biržai', 'Birzai'), ('Druskininkai', 'Druskininkai'), ('Elektrėnai', 'Elektrenai'), ('Gargždai', 'Gargzdai'), ('Ignalina', 'Ignalina'), ('Jonava', 'Jonava'), ('Joniškis', 'Joniskis'), ('Jurbarkas', 'Jurbarkas'), ('Kaišiadorys', 'Kaisiadorys'), ('Kalvarija', 'Kalvarija'), ('Kazlų Rūda', 'Kazlu Ruda'), ('Kėdainiai', 'Kedainiai'), ('Kelmė', 'Kelme'), ('Krekenava', 'Krekenava'), ('Kretinga', 'Kretinga'), ('Kupiškis', 'Kupiskis'), ('Kuršėnai', 'Kursenai'), ('Lazdijai', 'Lazdijai'), ('Lentvaris', 'Lentvaris'), ('Marijampolė', 'Marijampole'), ('Mažeikiai', 'Mazeikiai'), ('Molėtai', 'Moletai'), ('Naujoji Akmenė', 'Naujoji Akmene'), ('Nemenčinė', 'Nemencine'), ('Neringa', 'Neringa'), ('Pabradė', 'Pabrade'), ('Pagėgiai', 'Pagegiai'), ('Pakruojis', 'Pakruojis'), ('Palanga', 'Palanga'), ('Pasvalys', 'Pasvalys'), ('Plungė', 'Plunge'), ('Prienai', 'Prienai'), ('Radviliškis', 'Radviliskis'), ('Raseiniai', 'Raseiniai'), ('Rietavas', 'Rietavas'), ('Rokiškis', 'Rokiskis'), ('Šakiai', 'Sakiai'), ('Šalčininkai', 'Salcininkai'), ('Šilalė', 'Silale'), ('Šilutė', 'Silute'), ('Širvintos', 'Sirvintos'), ('Skuodas', 'Skuodas'), ('Švenčionys', 'Svencionys'), ('Tauragė', 'Taurage'), ('Telšiai', 'Telsiai'), ('Trakai', 'Trakai'), ('Ukmergė', 'Ukmerge'), ('Utena', 'Utena'), ('Varėna', 'Varena'), ('Vievis', 'Vievis'), ('Vilkaviškis', 'Vilkaviskis'), ('Visaginas', 'Visaginas'), ('Zarasai', 'Zarasai'), ('Nuotoliniu', 'Nuotoliniu')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_type',
            field=models.CharField(blank=True, choices=[('Intravert', 'Intravert'), ('Ekstravert', 'Ekstravert')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('USER', 'User'), ('FRIEND', 'Friend')], default='USER', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
