# Generated by Django 5.0.4 on 2024-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user_birthday_user_city_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('vyr', 'Vyr'), ('mot', 'Mot')], max_length=3, null=True),
        ),
    ]
