# Generated by Django 5.0.4 on 2024-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_color_four',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple')], default='#D9D9D9', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_color_one',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple')], default='#D9D9D9', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_color_three',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple')], default='#D9D9D9', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_color_two',
            field=models.CharField(choices=[('#D9D9D9', 'Gray'), ('#F6C4C4', 'Red'), ('#B2D8EE', 'Blue'), ('#B8F2C1', 'Green'), ('#F1B8F2', 'Purple')], default='#D9D9D9', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_four',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_one',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_three',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_two',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('User', 'User'), ('Friend', 'Friend')], default='User', max_length=6),
        ),
    ]
