# Generated by Django 5.0.4 on 2024-04-10 13:11

import antivienas.database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_user_interest_color_four_user_interest_color_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_one',
            field=models.ImageField(blank=True, null=True, upload_to=antivienas.database.models.user_img_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='img_three',
            field=models.ImageField(blank=True, null=True, upload_to=antivienas.database.models.user_img_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='img_two',
            field=models.ImageField(blank=True, null=True, upload_to=antivienas.database.models.user_img_upload_path),
        ),
    ]
