# Generated by Django 5.0.4 on 2024-04-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_friendsettings_user_account_holder_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guilty', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'New report'), (2, 'Being Reviewed'), (3, 'Disputed')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.order')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
