# Generated by Django 5.0.4 on 2024-04-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_dispute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendSettings',
            new_name='FriendSetting',
        ),
    ]
