# Generated by Django 5.0.4 on 2024-04-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_friendsettings_friendsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsetting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
        migrations.AddField(
            model_name='friendsetting',
            name='friend',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendsetting',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
