# Generated by Django 5.0.4 on 2024-04-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_order_created_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.AddField(
            model_name='dispute',
            name='was_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispute',
            name='is_guilty',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
