# Generated by Django 5.0.4 on 2024-04-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_rename_amount_paid_payment_amount_remove_payment_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='is_guilty',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='was_reviewed',
        ),
    ]
