# Generated by Django 5.0.4 on 2024-04-15 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_dispute_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
