# Generated by Django 5.0.4 on 2024-04-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='initiated',
            new_name='created',
        ),
    ]
