# Generated by Django 5.0.4 on 2024-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_rename_initiated_withdrawal_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='reported',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='reporter',
        ),
        migrations.AddField(
            model_name='dispute',
            name='reported_by_user',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
